org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.249
neo_version_range=[21.1.249,21.2)
loader_version_range=[1,)

## Mod Properties
mod_id=colossalfurnaces
mod_name=Colossal Furnaces
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.colossalfurnaces
mod_authors=GoldskinMC
mod_description=When bigger really is better - build massive furnaces with built-in automation.

## Dev Environment Mods
jei_file_id=8792638
the_one_probe_file_id=7292875
cyclops_core_file_id=8725069
colossal_chests_file_id=8748791
iron_furnaces_file_id=7034259
