org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.104
neo_version_range=[26.1.2.104,26.1.3)
loader_version_range=[1,)

## Mod Properties
mod_id=colossalfurnaces
mod_name=Colossal Furnaces
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.colossalfurnaces
mod_authors=GoldskinMC
mod_description=When bigger really is better - build massive furnaces with built-in automation.

## Dev Environment Mods
jei_file_id=8800648
the_one_probe_file_id=8797594
cyclops_core_file_id=8787208
colossal_chests_file_id=8748755
